// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhczk9SGkFJRqqlQU_J-_00hhJYqoTva0',
    appId: '1:885560086112:web:c8ef123c409b96175cfd05',
    messagingSenderId: '885560086112',
    projectId: 'sevy-controller',
    authDomain: 'sevy-controller.firebaseapp.com',
    storageBucket: 'sevy-controller.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgdk2sqfzhIn6naaCJvVEUAipk95bSqI',
    appId: '1:885560086112:android:e7b1dfb14cf42a625cfd05',
    messagingSenderId: '885560086112',
    projectId: 'sevy-controller',
    storageBucket: 'sevy-controller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ3SeqNkWJdP7yyNDhx293F0RmwmziKZ8',
    appId: '1:885560086112:ios:10b07a924ab90eda5cfd05',
    messagingSenderId: '885560086112',
    projectId: 'sevy-controller',
    storageBucket: 'sevy-controller.appspot.com',
    iosClientId: '885560086112-ua1gbc9kevfkfn527t0u6jv4s83e8521.apps.googleusercontent.com',
    iosBundleId: 'com.sevy.controller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ3SeqNkWJdP7yyNDhx293F0RmwmziKZ8',
    appId: '1:885560086112:ios:10b07a924ab90eda5cfd05',
    messagingSenderId: '885560086112',
    projectId: 'sevy-controller',
    storageBucket: 'sevy-controller.appspot.com',
    iosClientId: '885560086112-ua1gbc9kevfkfn527t0u6jv4s83e8521.apps.googleusercontent.com',
    iosBundleId: 'com.sevy.controller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhczk9SGkFJRqqlQU_J-_00hhJYqoTva0',
    appId: '1:885560086112:web:5d0b387a62b80bc85cfd05',
    messagingSenderId: '885560086112',
    projectId: 'sevy-controller',
    authDomain: 'sevy-controller.firebaseapp.com',
    storageBucket: 'sevy-controller.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBhczk9SGkFJRqqlQU_J-_00hhJYqoTva0',
    appId: '1:885560086112:web:637e414e9815a9135cfd05',
    messagingSenderId: '885560086112',
    projectId: 'sevy-controller',
    authDomain: 'sevy-controller.firebaseapp.com',
    storageBucket: 'sevy-controller.appspot.com',
  );
}
